// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { LeagueMatch, LeagueMatchTableId } from "./tables/LeagueMatch.sol";
import { LeagueOrganizer, LeagueOrganizerTableId } from "./tables/LeagueOrganizer.sol";
