// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILeagueManagementSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILeagueManagementSystem {
  function CHANGE_THIS_LeagueManagement_addLeagueMatch(bytes32 matchEntity) external;

  function CHANGE_THIS_LeagueManagement_removeLeagueMatch(bytes32 matchEntity) external;

  function CHANGE_THIS_LeagueManagement_addLeagueOrganizer(address account) external;

  function CHANGE_THIS_LeagueManagement_removeLeagueOrganizer(address account) external;
}
